
name: CI

on:
  push:
    branches: deploy

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v1
          
        - name: Install dependencies
          run: npm install
          
        - name: Build
          run: npm run deploy
